[feature] emotional parameter change
Azuki-bar/ceviord pull request #9
Opened 2022-01-31 15:30 UTC by gotti

Implement #5

2022-01-31 15:44 UTC, Azuki-bar commented on pkg/ceviord/handleMsg.go
> +func speak(text string) error {
この関数を`rawSpeak`にできませんか？ そのままCeVIOに流れることをアピールしたい

2022-01-31 15:45 UTC, gotti commented on pkg/ceviord/handleMsg.go
> +func speak(text string) error {
起きたらやります

2022-01-31 15:47 UTC, Azuki-bar requested changes

2022-02-01 08:13 UTC, gotti commented on pkg/ceviord/handleMsg.go
> +	parameters    *Parameters
はい

2022-02-01 08:16 UTC, Azuki-bar approved these changes

2022-02-01 08:22 UTC, merged